### ISSUE TITLE
npm run ERROR

### ISSUE THREAD

**Issue by tomatojacky** [vue-bulma/vue-admin#110]
ERROR in ./client/views/Home.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.0.7
- vue-template-compiler@2.0.8

**Comment by tomatojacky** [comment]
2.0.7 in package.json. set it to vue: 2.0.8...
then  do this :npm run dev   
you will see

ERROR in ./~/.0.0.1@vue-bulma-jump/src/index.js
Module parse failed: /Users/tomatoboy/develop/vueJs/vue-admin/node_modules/.0.0.1@vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
| 
 @ ./~/.6.2.8@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

**Comment by tomatojacky** [comment]
and then 
rm -rf node_modules && npm install -d 
has the same error

**Comment by fundon** [comment]
Landed in https://github.com/vue-bulma/vue-admin/releases/tag/v0.1.10.

**Comment by tomatojacky** [comment]
ok,i'll try  .
