### ISSUE TITLE
mac  项目不能运行

### ISSUE THREAD

**Issue by tomatojacky** [vue-bulma/vue-admin#114]
ERROR in ./~/.0.0.1@vue-bulma-jump/src/index.js
Module parse failed: /Users/tomatoboy/develop/vueJs/vue-admin/node_modules/.0.0.1@vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
| 
 @ ./~/.6.2.8@babel-loader/lib!./~/.10.0.1@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.1@vue-bulma-emoji/src/index.js
Module parse failed: /Users/tomatoboy/develop/vueJs/vue-admin/node_modules/.0.0.1@vue-bulma-emoji/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export filter from './filter'
| 
| export EmojiIcon from  './EmojiIcon'
 @ ./~/.6.2.8@babel-loader/lib!./~/.10.0.1@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Emoji.vue 52:0-52
 @ ./client/views/components/Emoji.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.4@vue-bulma-progress-tracker/src/index.js
Module parse failed: /Users/tomatoboy/develop/vueJs/vue-admin/node_modules/.0.0.4@vue-bulma-progress-tracker/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export StepItem from './StepItem'
| export default from './Tracker'
| 
 @ ./~/.6.2.8@babel-loader/lib!./~/.10.0.1@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/ProgressTracker.vue 76:0-71
 @ ./client/views/components/ProgressTracker.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

**Comment by tomatojacky** [comment]
rm -rf node_modules && npm install -d 
运行后 error 依旧

**Comment by fundon** [comment]
请问是升级到最新源码吗？

**Comment by tomatojacky** [comment]
是的，git clone 最新源码，已经试了多次了

**Comment by fundon** [comment]
请问你的 node、npm、webpack 都是多少？

**Comment by tomatojacky** [comment]
node v7.0.0
webpack -1.13.3
npm -v3.10.8
cnpm -v4.4.0

**Comment by fundon** [comment]
现在 master 分支使用的是 webpack v2 beta。

**Comment by fundon** [comment]
Landed in https://github.com/vue-bulma/vue-admin/releases/tag/v0.1.11.

**Comment by tomatojacky** [comment]
ok,我升级一下试试

**Comment by tomatojacky** [comment]
thanks
