### ISSUE TITLE
Does not work with IE

### ISSUE THREAD

**Issue by luventa** [vue-bulma/vue-admin#116]
## vue-admin version

0.1.11

### Description

Page is blank when working with IE **11 Edge Mode** .
Error: `SCRIPT438: Object doesn't support property or method 'assign'`
cannot eval code with function Object.assign in vue-nprogress.min.js 

I guess it's caused by webpack 2.x. Babel plugins cannot resolve this issue.

Sorry, my fault. Project works correctly with Microsoft Edge. I was testing it with IE 11 edge mode.

**Comment by fundon** [comment]
IE Edge 是支持的。很奇怪。

**Comment by fundon** [comment]
Consider https://buble.surge.sh/

**Comment by luventa** [comment]
按理说应该是支持Edge的，但是我在开发环境下确实有问题。
我用webpack1.x组装的项目引入nprogress，再用IE打开，是没有问题的。很奇怪

**Comment by fundon** [comment]
Releated #99.

**Comment by fundon** [comment]
See 7a88d26. 

这块如果真要支持 IE 低版本的，也会受 `vue-router` 限制，反正既不推荐。
