### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by torresyb** [vue-bulma/vue-admin#118]
以下是报错信息，不知道怎么回事？求解

ERROR in ./~/.0.0.1@vue-bulma-jump/src/index.js
Module parse failed: G:\works\vue-admin\node_modules\.0.0.1@vue-bulma-jump\src\index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
|
 @ ./~/.6.2.8@babel-loader/lib!./~/.10.0.2@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.1@vue-bulma-emoji/src/index.js
Module parse failed: G:\works\vue-admin\node_modules\.0.0.1@vue-bulma-emoji\src\index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export filter from './filter'
|
| export EmojiIcon from  './EmojiIcon'
 @ ./~/.6.2.8@babel-loader/lib!./~/.10.0.2@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Emoji.vue 52:0-52
 @ ./client/views/components/Emoji.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.0.4@vue-bulma-progress-tracker/src/index.js
Module parse failed: G:\works\vue-admin\node_modules\.0.0.4@vue-bulma-progress-tracker\src\index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export StepItem from './StepItem'
| export default from './Tracker'
|
 @ ./~/.6.2.8@babel-loader/lib!./~/.10.0.2@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/ProgressTracker.vue 76    :0-71
 @ ./client/views/components/ProgressTracker.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

**Comment by fundon** [comment]
请问已经更新到最新的源代码了吗？

**Comment by torresyb** [comment]
恩，是的，更新的最新代码。就是跑步起来，报上面的错

**Comment by fundon** [comment]
说下你的环境，node、npm 等。

**Comment by torresyb** [comment]
$ node -v
v6.9.1
$ npm -v
4.0.2
$ webpack -v
2.1.0-beta.27

**Comment by qcdys** [comment]
me too

**Comment by fundon** [comment]
Retry after `npm update -d`

**Comment by fundon** [comment]
@qcdys Is it still here?

**Comment by slipkinem** [comment]
我的情况也是报一样的错，是不是用 cnpm install 的原因？npm run dev/build error

**Comment by fundon** [comment]
Following the steps:

1. `rm -rf node_modules`
2. `npm i -d`
3. `npm run dev`

**Comment by violacase** [comment]
Me too.

webpack 2.1.0-beta.25
removed node_modules

command: npm i -d
echo'd:
```
npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v6.9.1
npm ERR! Windows_NT 10.0.14393
```
etc...

**Comment by qcdys** [comment]
好了

**Comment by fundon** [comment]
@qcdys 请问你是按照我的步骤来的吗？

**Comment by qcdys** [comment]
@fundon 是的
如果左侧的菜单区域可以做成向左收起的话、 那就更棒了

**Comment by luventa** [comment]
@qcdys 左侧菜单是可以收起的，浏览器宽度小于768就会自动隐藏菜单并在左上角显示打开菜单的按钮。
这段代码在App.vue的beforemount里面

**Comment by qcdys** [comment]
@luventa 好的、 谢啦

**Comment by violacase** [comment]
Sorry guys. I'm a Dutch guy. I can't read chinese.

**Comment by luventa** [comment]
@violacase qcdys strictly followed the steps that Fundon mentioned, and it worked fine.

**Comment by 15059492071** [comment]
我在国内，用cnpm，还是报同样的错

**Comment by violacase** [comment]
Sure you tested this on WIndows10 OS machine? 

Error log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Kees\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.9
3 info using node@v6.9.1
4 verbose stack Error: ENOENT: no such file or directory, open 'W:\___xamp\htdocs\apps\untouched\vue-admin\package.json'
4 verbose stack     at Error (native)
5 verbose cwd W:\___xamp\htdocs\apps\untouched\vue-admin
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kees\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
8 error node v6.9.1
9 error npm  v3.10.9
10 error path W:\___xamp\htdocs\apps\untouched\vue-admin\package.json
11 error code ENOENT
12 error errno -4058
13 error syscall open
14 error enoent ENOENT: no such file or directory, open 'W:\___xamp\htdocs\apps\untouched\vue-admin\package.json'
15 error enoent ENOENT: no such file or directory, open 'W:\___xamp\htdocs\apps\untouched\vue-admin\package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

```

**Comment by luventa** [comment]
@violacase can you check whether file `package.json` does exist under directory `vue-admin\` or not?
According to this line in your error log, it seems that the file is missing.
`no such file or directory, open 'W:\___xamp\htdocs\apps\untouched\vue-admin\package.json'`

**Comment by violacase** [comment]
It works!
Thx luventa et all. I don't know what went wrong. I tried to install it a couple of times last week but still it always failed.
Today I tried again to be absolutely sure and guess? All installed well without a single issue.
Thanks again. Keep up the good work!

**Comment by atmfans** [comment]
刚开始我也是怎么都报错，重新搞一下依赖也好了，还有你的  webpack配置项我貌似在哪见过

**Comment by fundon** [comment]
@luventa 可以把这段写进文档里面，看这里 https://github.com/vue-bulma/vue-admin/issues/118#issuecomment-265669461。

**Comment by luventa** [comment]
@fundon 没问题

**Comment by violacase** [comment]
I found out why it didn't work with me. This webpack uses port 8080. If this port is already served by another process the built errors. 
Hint: Alter the server configuration for using a FREE port.

**Comment by fundon** [comment]
@violacase I added an option `DEV_PORT` for dev server.

We can set env for running. If you use fish shell, try `env DEV_PORT=3030 npm run dev`.

**Comment by hjpyh-ybxrz** [comment]
为什么一直报错呢，npm i -d，是window 10的原因吗。。

**Comment by fundon** [comment]
@hjpyh-ybxrz 试过清空 `node_modules`吗?

**Comment by figoxu** [comment]
@atmfans  请问，你是如何从新搞一下依赖的？

**Comment by solody** [comment]
Me too,fuck，沒有一次能跑成功

**Comment by luventa** [comment]
Try [yarn](https://yarnpkg.com/). `npm install yarn -g`, then execute `yarn install` under the same directory you ran `npm install`. 
Registry `https://registry.npm.taobao.org/` could be useful.
Also, you can check [Vue admin wiki](https://github.com/vue-bulma/vue-admin/wiki/Guide) for more info.

跑不成功可能是因为依赖下载的问题。
可以先手动的删除整个node_modules文件夹
然后试一下[yarn](https://yarnpkg.com/这个工具。
另外cnpm可能不如把registry改成taobao镜像好用。
最后一定要注意，你需要装Git Bash，在Git Bash里面运行`npm install`或者`yarn install` （如果你安装了yarn）
有问题可以再查一下[Vue admin wiki](https://github.com/vue-bulma/vue-admin/wiki/Guide)

**Comment by fundon** [comment]
@figoxu 按这个步骤解决了吗？ https://github.com/vue-bulma/vue-admin/issues/118#issuecomment-265669461

**Comment by zyupo** [comment]
**Centos7 上面npm run dev  error报错解决方法：**
```
1. rm -rf node_modules
2. npm cache clean
3. npm i -d --registry=https://registry.npm.taobao.org
4. npm run dev
```

**Comment by soloSpring** [comment]
你好 我用了vue.cli已经成功运行了localhost:8080的cli模板了 然后关机睡觉了 第二天还在原路径下运行cpn run dev .命令行窗口说is related to npm not being able to find a file...

**Comment by figoxu** [comment]
@fundon I am using yarn install , It is ok 
https://github.com/vue-bulma/vue-admin/issues/130

**Comment by luventa** [comment]
@soloSpring 你这个是vue-cli的问题吧? cpn是哪个？

**Comment by soloSpring** [comment]
@luventa npm run dev 就是运行的那个命令 昨天输入这行命令之后 就直接打开模板了 今天就说 related to npm not being able to find a file...

**Comment by luventa** [comment]
@soloSpring 找个文件夹重新运行这些命令吧。这个错误信息很多情况都会出现，比如有可能你运行npm run dev的路径不正确。

`vue init webpack-simple test`
`cd test` -> 注意这句
`npm install` -> 确保install是成功的没有error
`npm run dev`

**Comment by soloSpring** [comment]
@luventa 啊..又要重新建立一个模板啊 我看了下 我进入了模板路径 就是cd text 后 再运行npm run dev 就弹出来这个
C:\Users\solofeng\sell\config\index.js:13
npm ERR! enoent and is related to npm not being able to find a filear static hosts such as
    ^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\solofeng\sell\build\dev-server.js:3:14)
    at Module._compile (module.js:570:32)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sell@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sell@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sell
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sell
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\solofeng\sell\npm-debug.log

我粗略看了下 好像说我npm 和node版本不对 可是npm和node是我昨天才下的 并且成功运行过的啊..TAT

**Comment by luventa** [comment]
@soloSpring 不是node版本问题。
·enoent and is related to npm not being able to find a filear static hosts such as·

八成是你网络连不上服务器

**Comment by guoshengbo** [comment]
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gsb\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass" "-d"
npm ERR! node v7.2.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gsb\Desktop\ll\vue-admin-0.1.12\npm-debug.log
在安装依赖的时候报这个错是为什么啊？ 我试着重新npm install node-sass 还是报这个错

**Comment by luventa** [comment]
@guoshengbo 我记得node-sass需要python 2.x
然后如果网络不好的话，node-sass的安装也会一直出错。建议挂个代理或者用淘宝镜像

**Comment by fundon** [comment]
都是 node-sass 的锅

**Comment by anson-GH** [comment]
change the config >index.js port: 8080 to other port eg, port: 8081
