### ISSUE TITLE
Is it the design or bug?

### ISSUE THREAD

**Issue by SidKwok** [vue-bulma/vue-admin#119]
![2016-12-03 15 58 32](https://cloud.githubusercontent.com/assets/13268747/20857804/81e35bea-b971-11e6-9184-1436216c3942.png)

See the close icon.

**Comment by fundon** [comment]
No,  whats your browser?
<img width="635" alt="screen shot 2016-12-05 at 17 05 21" src="https://cloud.githubusercontent.com/assets/27926/20879090/0be07f98-bb0d-11e6-8ca2-082e9996efa3.png">

**Comment by SidKwok** [comment]
Chrome 55.0.2883.75 (64-bit)

**Comment by fundon** [comment]
It's 55.0.2883.75 (64-bit) too.

**Comment by fundon** [comment]
Windows or Mac?

**Comment by SidKwok** [comment]
Mac

**Comment by fundon** [comment]
Maybe you reset the zoom.

**Comment by fundon** [comment]
I closed it. If it's stil there and reopen it.
