### ISSUE TITLE
Tabs design of code is not ok

### ISSUE THREAD

**Issue by dudesweet100** [vue-bulma/vue-admin#120]
When using http://monterail.github.io/vue-multiselect/#tagging, tabs class is overwriting style properties of the multiselect. 

Any suggestions on how to solve this problem, without going through css and overwriting styles?

**Comment by fundon** [comment]
Could you post code? Need more details.

**Comment by dudesweet100** [comment]
Just create a tabs panel and include tagging library. Tabs css overwrites tags css.

**Comment by fundon** [comment]
Update `vue-bulma-tabs` to v1.1.1.

**Comment by fundon** [comment]
@dudesweet100 It's ok?

**Comment by dudesweet100** [comment]
I am using github:vue-bulma/tabs. I see this is 1.0.0 version.

**Comment by dudesweet100** [comment]
Fixed, thx
