### ISSUE TITLE
can i use dev-tools with this project?

### ISSUE THREAD

**Issue by xchz** [vue-bulma/vue-admin#121]
chrome version:  55.0.2883.75 m (64-bit)
Vue.js devtools 2.3.1

npm run dev 
devtools has error...
error info : Vue.js is detected on this page. Open Chrome Devtools and look for the Vue panel.

**Comment by fundon** [comment]
See  https://github.com/vuejs/vue-devtools/issues/190.

**Comment by fundon** [comment]
Landed in https://github.com/vue-bulma/vue-admin/commit/2d01d10b4ea4f4f1dab1311c69d4e8abc68de7e7.
