### ISSUE TITLE
How to solve the problem?

### ISSUE THREAD

**Issue by bigggge** [vue-bulma/vue-admin#125]
```
 "dependencies": {
    "bulma": "^0.2.3",
    "vue": "^2.1.0"
  }
```

<img width="432" alt="2016-12-20 1 40 38" src="https://cloud.githubusercontent.com/assets/9855604/21339425/10532c66-c6ba-11e6-931b-106d9200f284.png">

如何引入bulma，~符号是什么意思？

**Comment by fundon** [comment]
看这个例子：https://github.com/vue-bulma/vue-admin/blob/master/client/App.vue#L61。
`~`：看 https://github.com/jtangelder/sass-loader#imports，主要是告诉 webpack 这不是一个相对路径，需要到 `node_modules` 中查找。

**Comment by bigggge** [comment]
@fundon 上面图中的问题不知怎么解决，跑起来没问题，但是ide会报错

**Comment by fundon** [comment]
那个提醒，`more...` 有帮助信息吗？

**Comment by bigggge** [comment]
@fundon Cannot resolve directory '~bulma'

**Comment by fundon** [comment]
用什么 IDE ？

**Comment by bigggge** [comment]
webstorm 2016.3

**Comment by luventa** [comment]
看看这个是否有帮助 (webstorm vue插件)[https://www.zhihu.com/question/39245838?sort=created]

**Comment by bigggge** [comment]
@luventa 插件没有用额

**Comment by luventa** [comment]
@bigggge 按照他说的先更新然后设置过了？

···
Mac端WebStorm用户。

command + , 打开偏好设置，选择plugins,，点击下方的browse repositories...

在打开窗口的搜索栏里打"vue"。 有两个插件

但是都不是官方的。

如果想要高亮显示*.vue文件，可以在File Types 选项里找到HTML，然后在下方手动添加*.vue，这样就有高亮啦。

作者：周左左
链接：https://www.zhihu.com/question/39245838/answer/80601310
来源：知乎
著作权归作者所有，转载请联系作者获得授权。
···

**Comment by bigggge** [comment]
@luventa 没用，你自己试过可以吗？

**Comment by luventa** [comment]
@bigggge 以前我用webstorm设置.vue的解析就好了，但是因为webstorm相对吃资源，所以现在的电脑用的是sublime然后装上vue高亮插件，是没有问题的。晚点我再试下webstorm，然后再告诉你。
先确定一下，是window系统的？

**Comment by bigggge** [comment]
@luventa  谢谢哦，我是mac的
