### ISSUE TITLE
https://admin.vuebulma.com/打不开

### ISSUE THREAD

**Issue by panwenhua** [vue-bulma/vue-admin#126]
1.https://admin.vuebulma.com/   打不开，
2.项目怎么安装

**Comment by luventa** [comment]
1. 请提供浏览器版本。低版本或经过二次开发的某些国内浏览器是不兼容的。具体兼容情况请看[Browser Support](https://github.com/vue-bulma/vue-admin/wiki#browser-support)
2. 请参考[Installation](https://github.com/vue-bulma/vue-admin/wiki/Guide#installation)

**Comment by panwenhua** [comment]
发现360浏览器默认开启了兼容模式，谢谢。
