### ISSUE TITLE
Transition changes in 2.1.7

### ISSUE THREAD

**Issue by StarpTech** [vue-bulma/vue-admin#129]
Hi, this change can influence all your components.

https://github.com/vue-bulma/modal/issues/6

**Comment by fundon** [comment]
Thank you.

BTW, welcome PR.

**Comment by luventa** [comment]
@StarpTech According to the [issue](https://github.com/vuejs/vue/issues/4576) I raised, we will skip over vue 2.1.7 to avoid this transition issue.
Thanks.

**Comment by fundon** [comment]
Vue updates to v2.1.8. Landed in https://github.com/vue-bulma/vue-admin/commit/6d7ad768cc3d12265d537aafc10dfcf28651883f.
