### ISSUE TITLE
How Can I Run That Project ?

### ISSUE THREAD

**Issue by figoxu** [vue-bulma/vue-admin#130]
![default](https://cloud.githubusercontent.com/assets/10055828/21589134/ad1bd11e-d129-11e6-910d-b2e0d74e7fc4.png)

![default](https://cloud.githubusercontent.com/assets/10055828/21589177/30decd44-d12a-11e6-9ef1-34cc201635c1.png)

$ npm -v
3.8.6
$ node -v
v5.12.0
$ cnpm -v
4.4.2
$ webpack -v
webpack 1.14.0

npm is too slow , I am use cnpm instead of npm .
I really want to run that code . Can you help me ?

**Comment by luventa** [comment]
@figoxu Try [yarn](https://yarnpkg.com/). `npm install yarn -g`, then execute `yarn install` under the same directory you ran `npm install`. 
Registry `https://yarnpkg.com/` could be useful.
Also, you can check [Vue admin wike](https://github.com/vue-bulma/vue-admin/wiki/Guide) for more info.

**Comment by figoxu** [comment]
@luventa  As Your Advice , I Success Run That Project . Thank You.
![default](https://cloud.githubusercontent.com/assets/10055828/21597431/ad414172-d185-11e6-81cc-71115684d223.png)
![default](https://cloud.githubusercontent.com/assets/10055828/21597433/b669e9ac-d185-11e6-975c-465322f092f6.png)

**Comment by luventa** [comment]
Welcome.
