### ISSUE TITLE
Demo not working on iPad 2

### ISSUE THREAD

**Issue by fractalf** [vue-bulma/vue-admin#131]
https://admin.vuebulma.com/ shows blank page in Safari, Firefox, Dolphin, Chrome on iPad 2

**Comment by TheNuclearCat** [comment]
On my iPad Pro its running fine on Firefox.
![img_0027](https://cloud.githubusercontent.com/assets/19869755/21608107/b97b129e-d1ba-11e6-9f84-d2b5bfb1248c.PNG)

**Comment by fractalf** [comment]
Ok, the "pro" line is different from the "iPad 2", so then we know it works for pro, but not for 2

**Comment by fundon** [comment]
What's the size of device?

**Comment by fundon** [comment]
Very strange

**Comment by MaizerGomes** [comment]
Better make sure you're using the latest version of those browsers. Some outdated browsers will fail to display.

**Comment by fractalf** [comment]
I think my 4 browsers are up to day, may be something else though.
I tried the Ipad 2 emulator at work, and it seems to be fine, so maybe some quirkness with my device.
