### ISSUE TITLE
Any plans to update to bulma 0.3.0?

### ISSUE THREAD

**Issue by alqu** [vue-bulma/vue-admin#139]
I saw that bulma 0.3.0 has been released recently.

They fixed a number of bugs in their [changelog](https://github.com/jgthms/bulma/blob/master/CHANGELOG.md#030).

Are there any plans on moving to their newer version?

BTW, I tried vue-admin out with bulma 0.3.0 and there only the background needs to be fixed to look OK. And yes, the colors are a bit different. I guess they renamed a couple of sass-variables.

Cheers

**Comment by luventa** [comment]
@alqu Yes, will do.
Also, there is another project under vue-bulma for providing basic components. 
We are currently working on that.  [vue-bulma/vue-bulma](https://github.com/vue-bulma/vue-bulma)

**Comment by alqu** [comment]
Thanks! I will have a look at that.

**Comment by mirari** [comment]
It seems like everything is OK in 0.3.1, except the input with icons, new style is like this:
```
<p class="control has-icon">
  <input class="input" type="email" placeholder="Email">
  <span class="icon is-small">
    <i class="fa fa-envelope"></i>
  </span>
</p>
```

**Comment by alqu** [comment]
...and select boxes:

in Bulma 0.2.3:
```html
<p class="control select">
  <select>...</select>
</p>
```
Now have to look like this in Bulma 0.3.1:
```html
<p class="control">
  <span class="select">
    <select>...</select>
  </span>
</p> 
```

**Comment by luventa** [comment]
commit for bulma 0.3.1 [dbb2157](https://github.com/vue-bulma/vue-admin/commit/dbb2157fc311f3dd38cedb2f684d30ab460570c5).

Feel free to add comment on the commit or this issue. Your feedback is really important for us! : )

**Comment by alqu** [comment]
I tested the vue admin demo page locally with dbb2157. No flaws found! Everything looks clean - and thanks for the axios-demo.
Browsers used for test: Safari 10.0.3 and Chrome.

This is probably a known bug: the Brace-Editor does not work in Safari.

**Comment by alqu** [comment]
The only thing here: most of the vue-bulma modules complain about a version mismatch:

> npm WARN vue-bulma-chartjs@1.0.1 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-message@1.1.0 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-card@1.0.1 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-brace@0.0.2 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-notification@1.1.0 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-switch@1.0.2 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-expanding@0.0.0 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-chartist@1.0.0 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-rating@1.0.0 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-progress-bar@1.0.0 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-emoji@0.0.1 requires a peer of bulma@^0.2 but none was installed.
npm WARN vue-bulma-jump@0.0.1 requires a peer of bulma@^0.2 but none was installed.

**Comment by mirari** [comment]
I also have the same problem, though not affecting the use

**Comment by luventa** [comment]
it's okay. Need to upgrade and publish related packages. I will fix these later.

**Comment by luventa** [comment]
@alqu I will test Brace on Safari. Thanks!

**Comment by fundon** [comment]
Please check http://admin.vuebulma.com.
