### ISSUE TITLE
"Maximum call stack size exceeded" error when opening certain pages

### ISSUE THREAD

**Issue by garethmcc** [vue-bulma/vue-admin#142]
Second issue posted in one day .. aren't I lucky :P

After cloning the git repom, running npm install to grab the node modules, I did a ```npm run dev``` to get the dev version open in my browser. However, when loading certain of the pages from the sidebar menu, it fails to load and any other link to a previous page that did previously load no longer works.

The error in Chrome console is always the folowing:

```
(unknown) RangeError: Maximum call stack size exceeded
    at VueComponent.Vue._render (eval at 1 (vendor.js:796), <anonymous>:2223:44)
    at VueComponent.updateComponent (eval at 1 (vendor.js:796), <anonymous>:2609:21)
    at Watcher.get (eval at 1 (vendor.js:796), <anonymous>:2934:27)
    at new Watcher (eval at 1 (vendor.js:796), <anonymous>:2926:12)
    at VueComponent.Vue._mount (eval at 1 (vendor.js:796), <anonymous>:2608:19)
    at VueComponent.Vue$2.$mount (eval at 1 (vendor.js:796), <anonymous>:6178:15)
    at init (eval at 1 (vendor.js:796), <anonymous>:1740:11)
    at createComponent (eval at 1 (vendor.js:796), <anonymous>:4174:9)
    at createElm (eval at 1 (vendor.js:796), <anonymous>:4117:9)
    at createChildren (eval at 1 (vendor.js:796), <anonymous>:4242:9)
    at createElm (eval at 1 (vendor.js:796), <anonymous>:4150:9)
```

The pages that this error repeatedly occurs for is:

- Charts/Chartist
- Charts/Peity
- Components/BackToTop
- Components/Brace
- Components/Collapse
- Components/DatePicker
- Components/Message
- Components/Modal
- Components/Notification
- Components/ProgressBarr
- Components/ProgressTracker
- Components/Quill
- Components/Rating
- Components/Slider
- Components/Tabs
- Components/Tooltip
- Components/Lory
- Tables/Handsontable

I am runnng on Gnome Ubuntu 16.04. NPM version 4.0.5 and Node version 7.4.0.

If you need anymore info for clarification please feel free to ask.

**Comment by luventa** [comment]
did you make any code change?
which version of browser are you using?

**Comment by garethmcc** [comment]
I've made no changes. I just re-cloned the git repo again, ran npm install and npm run dev to see if I had inadvertantly caused an issue but still the same problem.

**Comment by luventa** [comment]
it's really weird...
There is no exception with npm run dev but this exception in Chrome console, right?
Can you post some sections of code throw this exception? Thanks!

**Comment by garethmcc** [comment]
My steps to reproduce:
1. Clone git repo
2. Run ```npm install```
3. Run ```npm run dev```
4. Click link in nav menu listed above (any of them) and get the error in chrome.

There is no other code at all.

**Comment by garethmcc** [comment]
Not sure if it helps but I do have Webpack 4.0.5 installed as well.

**Comment by garethmcc** [comment]
I just had a fellow developer test it for me. He cloned, ```npm install```, ```npm run dev``` and on the same components listed above got the exact same error in Chrome console. 

Oh, and instead of Linux he's running a Windows system. So there definitely seems to be something up.

**Comment by luventa** [comment]
I guess it's related to webpack build process and I will test tomorrow (it's night here)
Btw, could you try webpack 2.x?

Also, Im using windows and I didnt install any version of webpack, only use the webpack 2.x in the dev dependencies

**Comment by luventa** [comment]
thanks again for your time

**Comment by garethmcc** [comment]
No problem. I made an error about my Webpack version in fact. I ran npm webpack -v for some reason instead of npm list webpack to check the version. I am running Webpack 2 and it still gives the same error.

**Comment by luventa** [comment]
Ah...yes, I thought that I'm obsolete because I never heard of webpack v4...
So you are using webpack 2 and the exception still occurs, right?
I still cannot repro your error on windows. And I want to know more about your situation with these questions.

1. Does bundle has any warning?
2. Did any dependency fail during `npm install` ?
3. Could you please add some `console.log('functionName')` any where you want, to check which method is called endless? For example:

**Comment by luventa** [comment]
@garethmcc I found a similar issue on SO
[Vue Uncaught RangeError Maximum call stack size exceeded](http://stackoverflow.com/questions/41545438/vue-uncaught-rangeerror-maximum-call-stack-size-exceeded)

**Comment by garethmcc** [comment]
1. No warnings
2. No dependancy fail

In order to try and replicate, perhaps delete your node_modules and do a fresh nmp install. Perhaps one of the modules has a new version that is causing the issue?

**Comment by pobrob** [comment]
I am experiencing the same thing on both Windows 10 and MacBook Pro IOS 10.12.2

**Comment by pobrob** [comment]
I did a little more work with it.  When you click on certain items (Handsontable, Quill, most of the items under components except switcher and emoji, the charts Chartist and Peity it does not like either) it stops working, however if you then click on something that did work and the click on refresh then it works again until you click on one of the bad ones.  Hopefully that helps.

**Comment by yaim** [comment]
Facing same issue on Fedora 23, node v6.9.4, npm 3.10.10
Just cloned an no change in the package...

**Comment by luventa** [comment]
@garethmcc Yes you're right! I upgraded my dependencies and same exception occurred. I will check witch library causes this issue. Sorry for keep asking about your local env, and thanks for raising this issue!

@yaim Don't worry I will figure out why. Thanks!

**Comment by luventa** [comment]
Found it. New version of vue-loader caused this issue. Let me make a quick fix on this, and please get the latest changes, remove the node_modules and execute `npm install` again. Thanks guys.

**Comment by pobrob** [comment]
Followed your instructions and it works great now, thanks!!  Great project

**Comment by holic-cl** [comment]
hi!, thanks for the patch, followed instructions and is working too.

**Comment by garethmcc** [comment]
Glad its fixed :)

**Comment by luventa** [comment]
Yes my fix shall works for time being.
Might caused by vue–loader or nonstandard component definition of vue-admin.
Will check later...

**Comment by pobrob** [comment]
Thought you ought to know that it appears this has affected the production build.  It worked correctly before you update.  If you run **npm run build** it fails.  Here is the beginning of the long message
WARNING in ./client/views/charts/Chartist.vue
Module build failed: TypeError: loader.charAt is not a function
    at ensureBang (/Users/rbpollock/vue-admin/node_modules/vue-loader/lib/loader.js:180:16)
    at getLoaderString (/Users/rbpollock/vue-admin/node_modules/vue-loader/lib/loader.js:145:18)
    at getRequireString (/Users/rbpollock/vue-admin/node_modules/vue-loader/lib/loader.js:80:7)
    at getRequire (/Users/rbpollock/vue-admin/node_modules/vue-loader/lib/loader.js:71:7)
    at /Users/rbpollock/vue-admin/node_modules/vue-loader/lib/loader.js:205:11
    at Array.forEach (native)
    at Object.module.exports (/Users/rbpollock/vue-admin/node_modules/vue-loader/lib/loader.js:198:18)

Not a big deal for me right now, but thought you ought to know.

**Comment by luventa** [comment]
Hey @pobrob . Thanks for your message.
It's okay I think, because it's not a permanent fix. 
Now the version mismatch between vue-loader and other vue libs caused this build issue.
I've raised an issue in vue-loader project and the maintainer has confirmed it's vue-loader's issue.

I will set the version of vue-loader to latest in vue-admin config after their change is ready.

**Comment by yaim** [comment]
@luventa would you please confirm which commit is the last stable point? (as stable as not facing this build issue). Thanks...

**Comment by luventa** [comment]
@yaim 	[db09565](https://github.com/vue-bulma/vue-admin/commit/db095656e6478ecdb60297da0134f9d2cc762ca6)

**Comment by nicaisa** [comment]
app.js:95570 [Vue warn]: Error in beforeCreate hook: "RangeError: Maximum call stack size exceeded"

(found in <Root>)
warn @ app.js:95570
logError @ app.js:96795
globalHandleError @ app.js:96790
handleError @ app.js:96779
callHook @ app.js:98007
Vue._init @ app.js:99689
Vue @ app.js:99770
./resources/js/app.js @ app.js:107312
__webpack_require__ @ app.js:64
0 @ app.js:109346
__webpack_require__ @ app.js:64
(anonymous) @ app.js:196
(anonymous) @ app.js:199
app.js:96799 RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (<anonymous>)
    at matchRoute (app.js:93821)
    at match (app.js:93703)
    at redirect (app.js:93763)
    at _createRoute (app.js:93802)
    at match (app.js:93704)
    at redirect (app.js:93763)
    at _createRoute (app.js:93802)
logError @ app.js:96799
globalHandleError @ app.js:96790
handleError @ app.js:96779
callHook @ app.js:98007
Vue._init @ app.js:99689
Vue @ app.js:99770
./resources/js/app.js @ app.js:107312
__webpack_require__ @ app.js:64
0 @ app.js:109346
__webpack_require__ @ app.js:64
(anonymous) @ app.js:196
(anonymous) @ app.js:199
