### ISSUE TITLE
关于页面title的问题

### ISSUE THREAD

**Issue by cgkoreyoshi** [vue-bulma/vue-admin#146]
如果想实现：每个路由URL都有自己的页面title，该如何做啊？
目前是webpack打包时指定的固定的title，无法每个页面自定义，麻烦指导下思路~

**Comment by luventa** [comment]
我觉得是这样的：以vue-admin为例，`app.js`中，在`router.beforeEach`里加一行
`document.title = route.name`
就达到目的了...

**Comment by cgkoreyoshi** [comment]
恩，找到好的方案了，多谢啦，你也可以看下 @luventa 
https://www.deboy.cn/set-wechat-title-in-vuejs-spa.html

**Comment by luventa** [comment]
好的，谢谢！
