### ISSUE TITLE
Load whole app all at once.

### ISSUE THREAD

**Issue by hifall** [vue-bulma/vue-admin#148]
First, nice project!

From the user experience, it seems that every time a new page is accessed, it's fetched from server and then displayed, right? This is just my guess because I am seeing a small delay each time a new page is accessed, although when the page is accessed again, it shows up instantly.

Is there a way to pack the whole app up, and have the browser load it when the app is first accessed? This would make every page show up instantly and provide a better user experience.

Thanks!

**Comment by luventa** [comment]
My first thought for this would be like this:
instead of using function `lazyLoading` in `client/store/modules/menu/*`, let's import the components at the beginning of each files.
And I think that would be helpful for your issue.

Thanks!

**Comment by hifall** [comment]
Glad to hear that this sounds like a light-weight fix.

If possible, could you kindly be a bit more specific on "let's import the components at the beginning of each file"? I am a newbie to vue/bulma.

Thanks.

**Comment by luventa** [comment]
for example:
> client\store\modules\menu\charts.js
```
import lazyLoading from './lazyLoading'

export default {
...
function generateRoutesFromMenu (menu = [], routes = []) {
  for (let i = 0, l = menu.length; i < l; i++) {
    let item = menu[i]
    if (item.path) {
====== ADD THIS SECTION TO PRE-LOAD COMPONENTS ======
      if (item.filePath) {
        routes.push({
          name: item.name,
          path: item.path,
          component: require(item.filePath)
        })
=============================================
      } else {
...
}
```

Btw, I think the delay caused by lazyloading is acceptable.

**Comment by hifall** [comment]
Thanks for you kind reply.

I will try this shortly.
