### ISSUE TITLE
How to use vue-admin example in a project? 

### ISSUE THREAD

**Issue by samayo** [vue-bulma/vue-admin#154]
Sorry if this question seems mundane, but I can't find documentation on how to integrate any of the examples in a project. 

If you talk a look at [bulma.io](http://bulma.io/documentation/modifiers/syntax/) docs, you can see the code and hence a simple copy-paste and it's done. 

Is there something I am missing, or do we have to check the source code on what/how to include the snippets? 

Also, thanks for this library, I plan to make a donation if you keep it up :)

**Comment by luventa** [comment]
Hi @samayo 
Here is the wiki page for vue-admin: [Wiki](https://github.com/vue-bulma/vue-admin/wiki)
If you want to integrate components of vue-admin to your own project, please check projects under  [vue-bulma](https://github.com/vue-bulma). These projects will show you sample codes.

**Comment by samayo** [comment]
@luventa  thanks. That's what I was looking for, sadly it uses `import` syntax which I can't use

**Comment by luventa** [comment]
@samayo `import` here is ES6 syntax which you can use babel to compile it.

**Comment by samayo** [comment]
@luventa Yeah, but I work on Virtualbox, which doesn't work well with symlinks, which means I can't use nodemodules. It's like working on windows environment :\

**Comment by luventa** [comment]
understood. Thanks
