### ISSUE TITLE
Pagination cant't be show

### ISSUE THREAD

**Issue by zhang0502jia** [vue-bulma/vue-admin#158]
can't be show Pagination with bulma3.0, and how to use with 2.0 - -

**Comment by luventa** [comment]
Vue-admin does not have pagination component, right?
If you need pagination styles, import `bulma/sass/components/pagination.sass` and related files.
Then follow the html example provided by [Bulma.io](http://bulma.io/documentation/components/pagination/)

**Comment by zhang0502jia** [comment]
Thanks, i created a  Pagination component
