### ISSUE TITLE
npm run dev error again

### ISSUE THREAD

**Issue by a1029563229** [vue-bulma/vue-admin#165]
`
  ✘  http://eslint.org/docs/rules/no-mixed-operators  Unexpected mix of '*' and '+'
  F:\plugins\vue-admin-master\client\views\charts\Chartjs.vue:87:64
        data_2: [1, 9, 3, 4, 5, 6, 7, 8, 2].map(e => Math.sin(e) * 25 + 25),
                                                                  ^

  ✘  http://eslint.org/docs/rules/no-mixed-operators  Unexpected mix of '*' and '+'
  F:\plugins\vue-admin-master\client\views\charts\Chartjs.vue:87:69
        data_2: [1, 9, 3, 4, 5, 6, 7, 8, 2].map(e => Math.sin(e) * 25 + 25),
                                                                       ^

✘ 2 problems (2 errors, 0 warnings)

Errors:
  2  http://eslint.org/docs/rules/no-mixed-operators
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/store/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi ./build/dev-client ./client/index.js

ERROR in ./~/.0.0.2@vue-bulma-jump/src/index.js
Module parse failed: F:\plugins\vue-admin-master\node_modules\.0.0.2@vue-bulma-jump\src\index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
|
 @ ./~/.6.3.2@babel-loader/lib!./~/.11.1.3@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/store/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi ./build/dev-client ./client/index.js

ERROR in ./~/.0.0.2@vue-bulma-emoji/src/index.js
Module parse failed: F:\plugins\vue-admin-master\node_modules\.0.0.2@vue-bulma-emoji\src\index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export filter from './filter'
|
| export EmojiIcon from  './EmojiIcon'
 @ ./~/.6.3.2@babel-loader/lib!./~/.11.1.3@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Emoji.vue 52:0-52
 @ ./client/views/components/Emoji.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/store/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi ./build/dev-client ./client/index.js

ERROR in ./~/.0.0.4@vue-bulma-progress-tracker/src/index.js
Module parse failed: F:\plugins\vue-admin-master\node_modules\.0.0.4@vue-bulma-progress-tracker\src\index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export StepItem from './StepItem'
| export default from './Tracker'
|
 @ ./~/.6.3.2@babel-loader/lib!./~/.11.1.3@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/ProgressTracker.vue 76:0-71
 @ ./client/views/components/ProgressTracker.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/store/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi ./build/dev-client ./client/index.js`

用cnpm i 然后就这样了
用yarn卡在1182/1183不动了
用npm -d卡在
`npm info git [ 'checkout', 'de2ab007455aa2587c552694c68583f94c9f2747' ]
npm info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
`

how to play the project...

**Comment by luventa** [comment]
先这样试试吧，手动删掉vue-admin下面的node_modules，然后`yarn install`
node sass下载很慢的，卡住不动不要急...cnpm有的地方并不好用

**Comment by a1029563229** [comment]
楼上的老兄 yarn install卡住了很久很久 我想问问 我开着蓝灯 要不要关了
一直卡在1182/1183不动
还有我刚才 npm i -d 成功了
但是Npm run dev 还是同样的报错

**Comment by fundon** [comment]
@a1029563229 报什么错误

**Comment by a1029563229** [comment]
就是我上面提到的 一模一样的错误
yarn还是继续卡着

**Comment by fundon** [comment]
上面有 eslint 的 `WARNING` 信息提醒，这个不影响

**Comment by a1029563229** [comment]
不是的 我进入浏览器localhost:8080
提示页面404 进不去页面...

**Comment by fundon** [comment]
感觉是 npm install 没装完，可以再试试删除 `node_modules` 目录，再 `npm install -d`

**Comment by a1029563229** [comment]
我已经尝试了多次了 我再试试吧 Yarn还卡着呢 谢谢你

**Comment by luventa** [comment]
@a1029563229 实在不行搞个ss翻墙吧 [捂脸]

**Comment by a1029563229** [comment]
我已经翻墙了 用的蓝灯...... ss过期了.. 不想续费 = =

**Comment by a1029563229** [comment]
npm i 也安装完了 然并卵！！！ = =

**Comment by luventa** [comment]
嗯？ss要钱？去搞aws啊
npm有时候并不是装完了...

**Comment by a1029563229** [comment]
我待会儿试试~

**Comment by a1029563229** [comment]
thanks

**Comment by luventa** [comment]
对了，也可以试试淘宝镜像，先装个nrm吧
`npm install nrm -g`

`nrm use taobao`

**Comment by a1029563229** [comment]
淘宝镜像也试过了... 我看了Node和npm版本都是够的 webpack也是2.0以上的 很奇怪

**Comment by lazyhero** [comment]
如果用cnpm去安装
```
deprecate plotly.js@1.24.0 › mapbox-gl@0.22.1 › feature-filter@^2.2.0 This package has been merged into the 'mapbox-gl-style-spec' package
deprecate plotly.js@1.24.0 › mapbox-gl@0.22.1 › mapbox-gl-function@^1.2.1 This package has been merged with the 'mapbox-gl-style-spec' package
deprecate plotly.js@1.24.0 › mapbox-gl@0.22.1 › geojson-rewind@0.1.0 › geojson-area@0.1.0 This module is now under the @mapbox namespace: install @
mapbox/geojson-area instead
deprecate plotly.js@1.24.0 › mapbox-gl@0.22.1 › unitbezier@^0.0.0 This module has moved: switch to @mapbox/unitbezier
deprecate plotly.js@1.24.0 › mapbox-gl@0.22.1 › shelf-pack@^1.0.0 This module is now under the @mapbox namespace: install @mapbox/shelf-pack instea
d
deprecate plotly.js@1.24.0 › mapbox-gl@0.22.1 › whoots-js@^2.0.0 This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
✔ All packages installed (1172 packages installed from npm registry, 2 packages installed from git, used 35s, speed 4.24MB/s, json 1316(7.42MB), ta
rball 141.67MB)
Recently updated (since 2017-02-25): 56 packages (detail see file /Users/me/Documents/code/vue-admin/node_modules/.recently_updates.txt)
  Today:
    → wysiwyg.css@0.0.2 › postcss-cli@2.6.0 › yargs@4.8.1 › read-pkg-up@1.0.1 › read-pkg@1.1.0 › load-json-file@1.1.0 › parse-json@2.2.0 › error-ex
@^1.2.0 (07:25:39)
    → wysiwyg.css@0.0.2 › node-sass@3.13.1 › request@^2.61.0 (12:42:42)
    → eslint@^3.12.2 (06:18:27)
    → html-webpack-plugin@2.28.0 › bluebird@^3.4.7 (05:49:31)
```
会发现有几个失效包 会被自动替换安装 然后执行npm run dev
会有3个ERROR
### 第一个
```
ERROR in ./~/.0.0.2@vue-bulma-jump/src/index.js
Module parse failed: /Users/me/Documents/code/vue-admin/node_modules/.0.0.2@vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
|
 @ ./~/.6.3.2@babel-loader/lib!./~/.11.1.4@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/BackToTop.vue 50:0-43
 @ ./client/views/components/BackToTop.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi ./build/dev-client ./client/index.js
```
### 第二个
```
ERROR in ./~/.0.0.2@vue-bulma-emoji/src/index.js
Module parse failed: /Users/me/Documents/code/vue-admin/node_modules/.0.0.2@vue-bulma-emoji/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export filter from './filter'
|
| export EmojiIcon from  './EmojiIcon'
 @ ./~/.6.3.2@babel-loader/lib!./~/.11.1.4@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Emoji.vue 52:0-52
 @ ./client/views/components/Emoji.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi ./build/dev-client ./client/index.js
```
### 第三个
```
ERROR in ./~/.0.0.4@vue-bulma-progress-tracker/src/index.js
Module parse failed: /Users/me/Documents/code/vue-admin/node_modules/.0.0.4@vue-bulma-progress-tracker/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export StepItem from './StepItem'
| export default from './Tracker'
|
 @ ./~/.6.3.2@babel-loader/lib!./~/.11.1.4@vue-loader/lib/selector.js?type=script&index=0!./client/views/components/ProgressTracker.vue 76:0-71
 @ ./client/views/components/ProgressTracker.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi ./build/dev-client ./client/index.js
```

当然如果用yarn或者npm安装……到node-sass那会非常卡 挂全局ss也得等很久 对 还在等……估计没戏了

建议开发人员还是自己试下重新安装依赖构建 发生的问题

**Comment by chenkang084** [comment]
我安装的时候也出现 包下载错误或者 安装完启动报错。
解决办法：1.删除node_modules下所有包，用yarn install，如果安装过程不报错，证明所有的包都下载ok了，启动就没有问题，如果不行话用方法2；
2.删除所有的包，cnpm install ，确保所有包安装完毕，npm run dev ，如果最后启动成功，但是 编译报错，把报错的 包 一个一个的删除，再去git 上面找到源码，下载源码，修改文件夹的名字和 package.json 里面的name一直，然后拖到 node_modules下面。依次替换所有的报错的包，最后再次启动，ok了。
如果还有问题，可以联系我。

**Comment by badis** [comment]
I am getting this error: 


 ERROR  Failed to compile with 1 errors                                                                                                                       9:41:40 AM

 error  in ./~/vue-bulma-jump/src/index.js

Module parse failed: /home/badis/Desktop/twitter/node_modules/vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export BackToTop from './BackToTop'
| export default from './Jump'
| 

 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/profile/Stream.vue 3:0-43
 @ ./src/components/profile/Stream.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Profile.vue
 @ ./src/components/Profile.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js


I think I need this solution but everything is written in Chinese.
Please post a translated version of the solution in English.

**Comment by a1029563229** [comment]
最后我用了ng2-admin
最后安利一下angular4 真的是太好用了
我是一名忠实的vue粉丝 但是做后台还是angular好用！
