### ISSUE TITLE
join vue-bulma organization 

### ISSUE THREAD

**Issue by netpi** [vue-bulma/vue-admin#168]
hello @fundon  

I am a full stack developer who like vue and bulma .

this is my first contribution to vue-bulma : https://github.com/netpi/vue-bulma-pagination .

I want to join vue-bulma in order to make more contributions .

Look forward to your reply 

> this is my github email - moon@netpi.me

**Comment by fundon** [comment]
Welcome! That's cool! I have invited you. Check email.

**Comment by fundon** [comment]
Thanks. Done.
