### ISSUE TITLE
solve ‘npm run dev ’ fail u need check this

### ISSUE THREAD

**Issue by lazyhero** [vue-bulma/vue-admin#172]
EN:
1.'package.json' missiong some plugin eg:mdi,animate.css
2.some plugin will takes a long wait eg:node-sass,ploty.js
3.there are some errors with vue-bulma-emoji i suggest that you remove it(check Emoji.vue)

CN
1.package.json依赖文件中缺少一些组件的依赖关系 如mdi和animate.css 
2.有一些插件要花些时间安装 比如node-sass和ploty.js 尤其是ploty.js
3.vue-bulma-emoji 有些错误 建议大家先移除

How to let it work

1.u need the 'ss' to connect npm well
2.u need remove yarn.lock 
3.install all dependencies except node-sass ploty.js and add mdi,animate.css

如何让它工作 打包成功
1.你需要一个翻墙利器 如ss
2.先移除yarn.lock
3.先不要安装node-sass ploty.js 并且把mdi,animate.css写到依赖里

**Comment by fundon** [comment]
@lazyhero 谢谢，可以把这些写个 PR，提交上来。

**Comment by luventa** [comment]
回头我找个地方加这些，wiki大家不爱看[捂脸]
