### ISSUE TITLE
Font assets generated path and referenced path don't match

### ISSUE THREAD

**Issue by Caiyeon** [vue-bulma/vue-admin#176]
After running `npm run build`, the fonts are generated under `public/assets/fonts`
However, when the webpage is served, the server tries to serve fonts from `public/assets/css/assets/fonts`

Changing `frontend/build/webpack.base.conf.js` query.name for font files will result in a change in both paths. In other words, changing query.name from `utils.assetsPath('fonts/[name].[hash:7].[ext]')` to `utils.assetsPath('css/[name].[hash:7].[ext]')` will result in fonts generated at `public/assets/css/fonts` and referenced at `public/assets/css/assets/css`, and does not solve the problem.

This issue does **not** occur when using `npm run dev`

**Comment by netpi** [comment]
hello @Caiyeon  
I can't reproduce your problem . show your development environment

**Comment by Caiyeon** [comment]
I am running `npm build` to generate the built files, and then serving the entire generated folder with Golang Echo framework `echo.Static("/", "public")`. I can reproduce this on Windows, OSX, and Debian

Here's what it looks like:
![image](https://cloud.githubusercontent.com/assets/6126493/24106325/c21f7870-0d44-11e7-81c8-4d1c1efd7d5c.png)

And chrome dev panel provides these errors:
![image](https://cloud.githubusercontent.com/assets/6126493/24106518/54dfcc0a-0d45-11e7-8782-78b52a0ed3a1.png)

Mousing over the asset displays what the server is trying to serve the ttf file from:
![image](https://cloud.githubusercontent.com/assets/6126493/24106544/6da1fd1c-0d45-11e7-8908-2356d0ca3ca9.png)

But as you know, the ttf files are not generated in `assets/css/assets/fonts`, they are generated in `assets/fonts`

**Comment by netpi** [comment]
it looks like this problem caused by your static server .  
try with `npm run start`  after `npm run build`

**Comment by Caiyeon** [comment]
@netpi `start` isn't a provided script in `package.json`
Can you provide the command that it maps to?

**Comment by netpi** [comment]
@Caiyeon  Sorry I forget `npm run start`  have not yet configured

* ` npm install -g node-static`
* `cd dist && static`

**Comment by Caiyeon** [comment]
![image](https://cloud.githubusercontent.com/assets/6126493/24132193/da4be534-0db0-11e7-859f-589ce1d2026c.png)

It's still trying to serve fonts from `/assets/css/assets/fonts/`

**Comment by Caiyeon** [comment]
Fixed it. It seems I was missing this:
https://github.com/vue-bulma/vue-admin/commit/6352f760af087f6e180f9495e4eb64f415716228#diff-b837e8e89bbf621827a64e0b2b0c0aa5

I had `publicPath: isELECTRON ? path.join(__dirname, '../dist/') : '',` in my repo instead of
`publicPath: isELECTRON ? path.join(__dirname, '../dist/') : '/',`

Sorry for the inconvenience @netpi :)

**Comment by netpi** [comment]
😆  thank you @Caiyeon

**Comment by BillGrim** [comment]
Well, I meet the same problem as I set publicpath from  **isELECTRON ? path.join(__dirname, '../dist/') : '/'** to **isELECTRON ? path.join(__dirname, '../dist/') : './'**. But my purpose is to change the absolute sourse request path (like /assets/js/*) to relative path (like ./assets/js/*) so that I can put all the files of vue-admin under /var/www/html/vue-admin/ instead of /var/www/html. So what files do I need to modify? Thanks.

**Comment by BillGrim** [comment]
@Caiyeon @netpi  Hello, guys. Do you know how to deal with my problem?
