### ISSUE TITLE
Add item to menu

### ISSUE THREAD

**Issue by rodrigooda** [vue-bulma/vue-admin#186]
Hi, im trying to add a item to menu, to do this i created a new folder called message in views and copy the Basic.vue from table to messages, and created the messages.js in menu folder, but the new menu does not show.
In the next is the messages.js
import lazyLoading from './lazyLoading'

export default {
  name: 'Messages',
  meta: {
    icon: 'fa-table',
    expanded: false
  },

  children: [
    {
      name: 'MessageTables',
      path: '/messages/basic',
      meta: {
        label: 'Basic Message Tables',
        link: 'messages/Basic.vue'
      },
      component: lazyLoading('messages/Basic')
    }
  ]
}

**Comment by zerosrat** [comment]
Did you import `./message.js` in `./index.js`?

**Comment by rodrigooda** [comment]
Its the vue2 admin template, in index.js has only 
import { app } from './app'
app.$mount('#app')

And i cant see where the others itens of menu are imported

**Comment by zerosrat** [comment]
Not `/client/index.js`, it is `/client/store/modules/menu/index.js`.

**Comment by rodrigooda** [comment]
In that index.js have this,
import Vue from 'vue'
import Vuex from 'vuex'
import pkg from 'package'
import * as actions from './actions'
import * as getters from './getters'

import app from './modules/app'
import menu from './modules/menu'

Vue.use(Vuex)

const store = new Vuex.Store({
  strict: true,  // process.env.NODE_ENV !== 'production',
  actions,
  getters,
  modules: {
    app,
    menu
  },
  state: {
    pkg
  },
  mutations: {
  }
})

export default store

is importing menu, and inside menu i put the messages.js
import lazyLoading from './lazyLoading'

export default {
  name: 'Messages',
  meta: {
    icon: 'fa-table',
    expanded: false
  },

  children: [
    {
      name: 'MessageTables',
      path: '/messages/basic',
      meta: {
        label: 'Basic Message Tables',
        link: 'messages/Basic.vue'
      },
      component: lazyLoading('messages/Basic')
    }
  ]
}

**Comment by rodrigooda** [comment]
zerosrat i found the import in /client/store/modules/menu/index.js, its working now, thank you so much!
