### ISSUE TITLE
this.$auth.token() returns [object Object] 

### ISSUE THREAD

**Issue by Kuchiriel** [vue-bulma/vue-admin#194]
I have already [reported this problem on vue-auth repository](https://github.com/websanova/vue-auth/issues/142#issuecomment-296158498), but this does not seem to be vue-auth problem.

**Comment by Kuchiriel** [comment]
I've discovered the problem, vue-admin don't receive tokens in the request header by default, instead, it receives from the body of the request. I was trying to send in the header from the beginning. Some special reason for this kind of authentication? Thanks in advance!

**Comment by zhihuiFan** [comment]
hi @Kuchiriel   I run into the exact same issue, could you share what did you do to fix this issue?

**Comment by zhihuiFan** [comment]
I have figure out the question.
The question @Kuchiriel  mentioned here is about the code in client/app.js

```
    response: function (res) {
      // Get Token from response body
      return res.data
    }
```
There is nothing wrong in vue-admin,  but the user need to check their own backend to see how to set the token. take mine for example:  it is res.data.accessToken.

I run into another issue is:
I use a webpack proxy to proxy the api to a backend server,  I set the correct header and send it to webpack proxy,  however the proxy discard the header when it proxy to the real backend server...

```
    proxyTable: {
      '/api': {
        target: 'http://localhost:8080/',
	  changeOrigin: true,
      }
```

**Comment by Kuchiriel** [comment]
@zhihuiFan Hello
This is my vue-auth configuration
![image](https://user-images.githubusercontent.com/4648891/32131662-c153eadc-bb92-11e7-8690-35f6f9322dee.png)

It extracts the token from the body of the request, must be `Bearer + Token`
![image](https://user-images.githubusercontent.com/4648891/32131666-df98580c-bb92-11e7-92f0-8e458eaaf315.png)

As you can see, if I log in, I can get from the localStorage.
![image](https://user-images.githubusercontent.com/4648891/32131659-b026c4a0-bb92-11e7-945e-412733d997e6.png)
