### ISSUE TITLE
many  module is deprecated

### ISSUE THREAD

**Issue by glennWang** [vue-bulma/vue-admin#201]
as title say ，many module is deprecated

Could you update the package.json ？

npm WARN deprecated husl@5.0.3: Project renamed to HSLuv
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
npm WARN deprecated mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
npm WARN deprecated whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead

**Comment by eddyekofo94** [comment]
True, so useful but needs a huge update, have a hardtime trying to use to myself

**Comment by Dmitry1987** [comment]
JavaScript world moves so fast and library owners change and move things all the time so it's impossible to build a project based on open source libs that will JUST WORK for years. I really hate this .... why moving and renaming the libraries all the time? this is so annoying...

**Comment by luventa** [comment]
will update soon...
@Dmitry1987 Agreed [cry]

**Comment by luventa** [comment]
Forget to reply this issue. 
Vue admin dependency [plotly.js](https://github.com/plotly/plotly.js) is using mapbox as its dependency...
So, we need to wait for it to fix these issue.

**Comment by humblecoder** [comment]
Also, "package" npm package (as required in this app's vuex store) has been deprecated for some time.  They recommend using "https://github.com/npm/read-package-json" which itself has issues.  Also, many of the components and related npm/yarn requirements aren't conducive to integration with other frameworks.  Definitely appreciate the hard work that has gone into this project, but it needs to be stripped down and overhauled.
