### ISSUE TITLE
Setting 'config.builld.assetsPublicPath' in Production building doesn't work

### ISSUE THREAD

**Issue by Calvin-he** [vue-bulma/vue-admin#203]
The variable `publicPath`  in 'build.webpack.prod.conf.js'  is like this below:
    `publicPath: isELECTRON ? path.join(__dirname, '../dist/') : '/',`

I think the correct way should be: 
    `publicPath: isELECTRON ? path.join(__dirname, '../dist/') : 'config.builld.assetsPublicPath',`

**Comment by luventa** [comment]
Yes you'r right. I'm correcting it now.
