### ISSUE TITLE
SweetAlert in vue-admin

### ISSUE THREAD

**Issue by ranaclyde** [vue-bulma/vue-admin#218]
How can I use sweetalert in vue-admin? Some help?

**Comment by rafamedina** [comment]
I think you could use it, with or without vue-admin

take a look at this repo, it's a integration with vuejs (the main point):

https://github.com/lishengzxc/vue-sweetalert

![image](https://user-images.githubusercontent.com/26074131/29174564-eadf4644-7da3-11e7-9cd1-db37dd16256e.png)

**Comment by ranaclyde** [comment]
@rafamedina Thanks. Its work fine
