### ISSUE TITLE
Is this still maintainable? How to contribute?

### ISSUE THREAD

**Issue by mandaputtra** [vue-bulma/vue-admin#254]
Seems the last commit is a year ago. And now bulma are v0.7 then is this still mantainable? How to contribute?

**Comment by fundon** [comment]
I have found several small partners and we will continue to maintain them.

**Comment by mandaputtra** [comment]
Thanks, any future guidelines on how to contribute? or you just preferred others people to open up an issue?

**Comment by mandaputtra** [comment]
I see you refactoring it, hope the best for you and team ! 😄 👍
