### ISSUE TITLE
Suggestion - Add 'show code' section to the demo pages

### ISSUE THREAD

**Issue by edwinyzh** [vue-bulma/vue-admin#62]
This is a very very cool project, Bulma css is very human-friendly and looks nice out of the box already, and vue-admin take the visual effects to a new level, the demo pages are quick (I hate heavy pages :P) and lightweight, well done, bro!

Just one suggestion - if it's possible - add 'show code' sections to each demo pages, so that one can easily check the code behind and knows how it works.

**Comment by fundon** [comment]
Good sounds. I like this idea.

**Comment by luventa** [comment]
landed
