### ISSUE TITLE
error Unexpected token export

### ISSUE THREAD

**Issue by vanderlin** [vue-bulma/vue-admin#93]
When pulling in some of the components I get this error:

`BaseModal.js?6143:2 Uncaught SyntaxError: Unexpected token export(…)`

I'm not sure why but in my wepack.config if i add this to the loader for js like you have it in your settings. `exclude: [new RegExp(`node_modules\\${path.sep}(?!vue-bulma-.*)`)]` it works. I'm just wondering what is happening?

**Comment by wikidson** [comment]
same problem...

**Comment by wikidson** [comment]
ERROR in multi app
Module not found: Error: Can't resolve 'babel' in '/Users/wikid/outsourcing/vue-admin'
 @ multi app

ERROR in multi vendor
Module not found: Error: Can't resolve 'babel' in '/Users/wikid/outsourcing/vue-admin'
 @ multi vendor

ERROR in multi app
Module not found: Error: Can't resolve 'babel' in '/Users/wikid/outsourcing/vue-admin'
 @ multi app

**Comment by wikidson** [comment]
npm run dev:
happen the following errors:


ERROR in multi app
Module not found: Error: Can't resolve 'babel' in '/Users/wikid/outsourcing/vue-admin'
 @ multi app

ERROR in multi vendor
Module not found: Error: Can't resolve 'babel' in '/Users/wikid/outsourcing/vue-admin'
 @ multi vendor

ERROR in multi app
Module not found: Error: Can't resolve 'babel' in '/Users/wikid/outsourcing/vue-admin'
 @ multi app

**Comment by fundon** [comment]
Landed in #95
