### ISSUE TITLE
Working on IE9

### ISSUE THREAD

**Issue by victorkurauchi** [vue-bulma/vue-admin#99]
Hi, have you tried to deploy over Microsoft IIS to work with IE9 before ?  I've tried today (uploading just the dist folder after npm run build) and it was not possible to make it work.

My application loads, but many events/components are not working, i.e NProgress, Datepicker, blur events.

I got this error while trying to work with NProgress:

`SCRIPT438: Object doesn't support property or method 'setPrototypeOf' `

I don't know if i need to use es6-shim or polyfills to get the application running in IE9. Do you know about that?
Thanks in advance.

**Comment by luventa** [comment]
Hi @victorkurauchi 
According to [bulma-browser-support](https://github.com/jgthms/bulma#browser-support)
Bulma does not fully support IE9.

**Comment by cgkoreyoshi** [comment]
nprogress does not support IE

**Comment by fundon** [comment]
Landed in https://github.com/vue-bulma/nprogress/releases/tag/v0.1.4.
